### ISSUE TITLE
Readme failure

### ISSUE THREAD

**Issue by BrianNewsom** [gitlytics/Gitlytics#17]
@steventang2013 
I tried a repo and hit an error.  It seems if there is no readme the call fails. 
![screenshot 2015-03-28 at 11 11 09 am](https://cloud.githubusercontent.com/assets/3268911/6881980/3d5f5e2c-d53b-11e4-9800-ad479f5b7824.png)

Could you look into this?

**Comment by steventang2013** [comment]
Good catch. Issue has been fixed. Let me know if there is anything else you need.

**Comment by BrianNewsom** [comment]
Good work! Thanks man
