### ISSUE TITLE
Search redirect loop

### ISSUE THREAD

**Issue by BrianNewsom** [gitlytics/Gitlytics#18]
An empty search gives
![screenshot 2015-03-28 at 6 32 48 pm](https://cloud.githubusercontent.com/assets/3268911/6883570/ebf6d18a-d578-11e4-8857-74943f9c53ab.png)
There should be a way to ensure the form isn't empty but I don't know how to do this.

**Comment by nicot** [comment]
Fixed as of 81964544da8a8479a5422776841aca33c1d9cab1.
